# Script pour créer la structure d'intégration des API

$apiFolders = @(
    "api_integration_tools/automation_apis",
    "api_integration_tools/developer_tools_apis", 
    "api_integration_tools/integration_apis",
    "dev_productivity_prompts"
)

$apiFiles = @{
    "api_integration_tools/automation_apis/social_media_apis.md" = "# Prompts pour les API de réseaux sociaux`n`n## Twitter/X Scraper`n**Objectif** : Extraire des données de Twitter/X pour analyse de contenu ou veille stratégique`n**Prompt** : `"Utilise l'API Twitter Scraper (Ultimate) pour collecter des tweets pertinents sur [sujet] dans la période [dates]. Analyse les tendances, les hashtags populaires et les interactions. Fournis un rapport avec les insights clés et les comptes influents.`"`n`n## Instagram Post Scraper`n**Objectif** : Analyser les publications Instagram pour une campagne de marketing`n**Prompt** : `"Utilise l'API Instagram Post & Video Scraper pour extraire les données de publication pour [compte ou hashtag]. Analyse les métriques d'engagement, les types de contenu les plus performants et les tendances visuelles.`"`n`n## LinkedIn Jobs Scraper`n**Objectif** : Analyser le marché de l'emploi pour un poste spécifique`n**Prompt** : `"Utilise l'API LinkedIn Jobs Scraper pour collecter les offres d'emploi pour [poste] dans [localisation]. Identifie les compétences les plus demandées, les tendances salariales et les entreprises les plus actives.`""
    "api_integration_tools/automation_apis/web_scraping_apis.md" = "# Prompts pour les API de scraping web`n`n## Google Search Results Scraper`n**Objectif** : Extraire des résultats de recherche Google pour analyse de contenu`n**Prompt** : `"Utilise l'API Google Search Results Scraper pour collecter des résultats de recherche sur [sujet]. Analyse les domaines les plus présents, les tendances de contenu et les mots-clés associés.`"`n`n## Amazon Product Scraper`n**Objectif** : Analyser les produits Amazon pour veille concurrentielle`n**Prompt** : `"Utilise l'API Amazon Product Scraper pour collecter des données sur [produit ou catégorie]. Analyse les prix, les évaluations, les caractéristiques et les tendances du marché.`""
    "api_integration_tools/automation_apis/data_extraction_apis.md" = "# Prompts pour les API d'extraction de données`n`n## YouTube Transcript Downloader`n**Objectif** : Extraire des transcriptions YouTube pour analyse de contenu`n**Prompt** : `"Utilise l'API YouTube Transcript Downloader pour extraire les transcriptions de vidéos sur [sujet]. Analyse les thèmes principaux, les mots-clés récurrents et les structures narratives.`""
    "api_integration_tools/automation_apis/workflow_automation_apis.md" = "# Prompts pour les API d'automatisation de workflow`n`n## Any Website URL to Article Summarizer`n**Objectif** : Résumer automatiquement des articles web`n**Prompt** : `"Utilise l'API Any Website URL to Article Summarizer pour résumer automatiquement le contenu de [URL]. Génère un résumé structuré avec les points clés, les insights et les recommandations.`""
    "api_integration_tools/developer_tools_apis/code_analysis_apis.md" = "# Prompts pour les API d'analyse de code`n`n## AI Code Review Agent`n**Objectif** : Effectuer des revues de code automatisées`n**Prompt** : `"Utilise l'API AI Code Review Agent pour analyser le code dans [dossier ou fichier]. Identifie les bugs potentiels, les problèmes de sécurité et les opportunités d'amélioration. Fournis des recommandations concrètes.`""
    "api_integration_tools/developer_tools_apis/testing_apis.md" = "# Prompts pour les API de test`n`n"
    "api_integration_tools/developer_tools_apis/monitoring_apis.md" = "# Prompts pour les API de surveillance`n`n"
    "api_integration_tools/developer_tools_apis/deployment_apis.md" = "# Prompts pour les API de déploiement`n`n"
    "api_integration_tools/integration_apis/validation_apis.md" = "# Prompts pour les API de validation`n`n## Vies VAT number validation`n**Objectif** : Valider des numéros de TVA pour la conformité fiscale`n**Prompt** : `"Utilise l'API Vies VAT number validation pour vérifier la validité du numéro de TVA [numéro]. Confirme la conformité fiscale et l'identité de l'entreprise pour les transactions B2B.`""
    "api_integration_tools/integration_apis/search_apis.md" = "# Prompts pour les API de recherche`n`n## GPT Search [Private API]`n**Objectif** : Effectuer des recherches avancées avec GPT`n**Prompt** : `"Utilise l'API GPT Search pour effectuer une recherche approfondie sur [sujet]. Fournis une synthèse structurée avec des sources vérifiables et des recommandations basées sur les dernières informations disponibles.`""
    "api_integration_tools/integration_apis/content_generation_apis.md" = "# Prompts pour les API de génération de contenu`n`n## LinkedIn Posts Generator`n**Objectif** : Générer des publications LinkedIn avec IA`n**Prompt** : `"Utilise l'API LinkedIn Posts Generator pour créer des publications engageantes sur [sujet]. Produis du contenu aligné avec la stratégie de marque et optimisé pour l'engagement.`""
    "api_integration_tools/integration_apis/business_intelligence_apis.md" = "# Prompts pour les API d'intelligence d'affaires`n`n## Company Research Intelligence Tool`n**Objectif** : Générer des rapports d'intelligence d'entreprise`n**Prompt** : `"Utilise l'API Company Research Intelligence Tool pour créer un rapport complet sur [entreprise ou domaine]. Inclus des informations sur la structure, les produits, la concurrence, les tendances du marché et les opportunités.`""
    "api_integration_tools/api_integration_guides.md" = "# Guides d'intégration des API`n`n## Guide de démarrage rapide`n`n1. Identifiez le besoin spécifique dans votre projet`n2. Recherchez l'API correspondante dans les catégories appropriées`n3. Adaptez le prompt fourni à votre contexte spécifique`n4. Intégrez l'API dans votre workflow de développement`n5. Surveillez les résultats et optimisez selon les besoins`n`n## Bonnes pratiques`n`n- Respectez toujours les limites de taux d'utilisation des API`n- Mettez en cache les résultats lorsque possible pour réduire les appels répétés`n- Gérez les erreurs et exceptions de manière appropriée`n- Documentez l'utilisation des API dans votre projet`n- Vérifiez la conformité avec les politiques d'utilisation des services"
    "dev_productivity_prompts/api_automation_patterns.md" = "# Modèles d'automatisation avec API`n`n## Modèle de scraping de contenu`n- Identifie la source de données`n- Configure les paramètres d'extraction`n- Définit les transformations de données`n- Planifie les exécutions récurrentes`n- Gère les erreurs et la journalisation`n`n## Modèle de validation de données`n- Définit les critères de validation`n- Intègre les API de validation appropriées`n- Met en place des contrôles de qualité`n- Génère des rapports de conformité`n- Alertes en cas de non-conformité"
    "dev_productivity_prompts/scraping_workflows.md" = "# Workflows de scraping`n`n## Workflow d'analyse de marché`n1. Utilise Google Search Results Scraper pour identifier les concurrents`n2. Applique Amazon Product Scraper pour analyser les prix et les caractéristiques`n3. Utilise LinkedIn Jobs Scraper pour comprendre les tendances de l'emploi`n4. Génère un rapport d'analyse de marché consolidé`n`n## Workflow de veille concurrentielle`n1. Configure les alertes pour les nouveaux produits concurrentiels`n2. Suit les évaluations et commentaires clients`n3. Analyse les stratégies de contenu sur les réseaux sociaux`n4. Produit des recommandations stratégiques"
    "dev_productivity_prompts/integration_boilerplates.md" = "# Boilerplates d'intégration`n`n## Boilerplate d'intégration API`n```javascript`n// Configuration de base`nconst apiConfig = {`n  apiKey: process.env.API_KEY,`n  baseUrl: 'https://api.example.com',`n  timeout: 10000`n};`n`n// Fonction d'appel API`nasync function callAPI(endpoint, params) {`n  try {`n    const response = await fetch(`${apiConfig.baseUrl}${endpoint}`, {`n      method: 'GET',`n      headers: {`n        'Authorization': `Bearer ${apiConfig.apiKey}`,`n        'Content-Type': 'application/json'`n      },`n      ...params`n    });`n    `n    if (!response.ok) {`n      throw new Error(`API call failed: ${response.status}`);`n    }`n    `n    return await response.json();`n  } catch (error) {`n    console.error('API call error:', error);`n    throw error;`n  }`n}`n```"
    "README_API_INTEGRATION.md" = "# Intégration des API dans le projet`n`nCe dossier contient des prompts et des guides pour intégrer efficacement les API dans vos projets de développement. Les API proviennent du dépôt `"API-mega-list`" qui contient plus de 10 000 API prêtes à l'emploi.`n`n## Catégories d'API`n`n- **Automation APIs** : Outils pour automatiser diverses tâches`n- **Developer Tools APIs** : Outils pour aider au développement et à l'analyse de code`n- **Integration APIs** : Outils pour intégrer des services tiers`n`n## Utilisation`n`n1. Identifiez le besoin dans votre projet`n2. Consultez les prompts dans la catégorie appropriée`n3. Adaptez le prompt à votre contexte spécifique`n4. Intégrez l'API dans votre workflow`n`n## Avantages`n`n- Gain de temps important dans le développement`n- Accès à des données riches pour l'analyse`n- Automatisation de tâches répétitives`n- Amélioration de la productivité des développeurs"
}

# Créer les dossiers
foreach ($folder in $apiFolders) {
    $folderPath = Join-Path -Path "." -ChildPath $folder
    if (!(Test-Path -Path $folderPath)) {
        New-Item -ItemType Directory -Path $folderPath -Force
        Write-Host "Dossier créé: $folderPath"
    }
}

# Créer les fichiers avec contenu initial
foreach ($file in $apiFiles.GetEnumerator()) {
    $filePath = Join-Path -Path "." -ChildPath $file.Key
    if (!(Test-Path -Path $filePath)) {
        $file.Value | Out-File -FilePath $filePath -Encoding UTF8
        Write-Host "Fichier créé: $filePath"
    }
}